# Generated by Django 3.0.7 on 2020-06-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_photo',
            field=models.ImageField(blank=True, upload_to='photo/%d/%m/%Y'),
        ),
    ]
